"""upgrade proofs model

Revision ID: 378a75ecfd80
Revises: fbfc9c42468f
Create Date: 2024-06-10 09:59:57.712262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '378a75ecfd80'
down_revision: Union[str, None] = 'fbfc9c42468f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_task_completions', 'status')
    op.drop_column('activity_task_completions', 'checked_on')
    op.add_column('task_completion_proof', sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='taskcompletionstatus'), server_default='PENDING', nullable=False))
    op.add_column('task_completion_proof', sa.Column('checked_on', sa.DateTime(timezone=True), nullable=True))
    op.add_column('task_completion_proof', sa.Column('is_checked', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_completion_proof', 'is_checked')
    op.drop_column('task_completion_proof', 'checked_on')
    op.drop_column('task_completion_proof', 'status')
    op.add_column('activity_task_completions', sa.Column('checked_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('activity_task_completions', sa.Column('status', postgresql.ENUM('PENDING', 'VERIFIED', 'REJECTED', name='taskcompletionstatus'), server_default=sa.text("'PENDING'::taskcompletionstatus"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
