"""add status model for tasks

Revision ID: c033d36c2665
Revises: 378a75ecfd80
Create Date: 2024-06-10 10:29:09.525144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c033d36c2665'
down_revision: Union[str, None] = '378a75ecfd80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_task_user_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('JOIN', 'LEAVE', name='activitytaskusereventtype'), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('activity_task_id', sa.Integer(), nullable=False),
    sa.Column('added_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_task_id'], ['activity_task.id'], ),
    sa.ForeignKeyConstraint(['telegram_id'], ['user.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_task_user_events')
    # ### end Alembic commands ###
