"""add log models, add hidden field

Revision ID: c0a0526bb1a2
Revises: e8e0646f9e82
Create Date: 2024-06-09 18:39:36.040585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a0526bb1a2'
down_revision: Union[str, None] = 'e8e0646f9e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_user_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('JOIN', 'LEAVE', name='activityusereventtype'), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('added_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['telegram_id'], ['user.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('activity_task_completions', sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_task_completions', 'is_hidden')
    op.drop_table('activity_user_events')
    # ### end Alembic commands ###
