"""fix model key

Revision ID: c4f916028966
Revises: a5519b82cb2d
Create Date: 2024-06-04 21:19:11.949940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4f916028966'
down_revision: Union[str, None] = 'a5519b82cb2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_task_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('activity_task_id', sa.Integer(), nullable=False),
    sa.Column('proof_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='taskcompletionstatus'), server_default='PENDING', nullable=False),
    sa.Column('sent_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('checked_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_task_id'], ['activity_task.id'], ),
    sa.ForeignKeyConstraint(['proof_id'], ['task_completion_proof.id'], ),
    sa.ForeignKeyConstraint(['telegram_id'], ['user.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('activity_task_completion')
    op.alter_column('activity_task', 'niche_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_task', 'niche_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('activity_task_completion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('activity_task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proof_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'VERIFIED', 'REJECTED', name='completionstatus'), server_default=sa.text("'PENDING'::completionstatus"), autoincrement=False, nullable=False),
    sa.Column('sent_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('checked_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_task_id'], ['activity_task.id'], name='activity_task_completion_activity_task_id_fkey'),
    sa.ForeignKeyConstraint(['proof_id'], ['task_completion_proof.id'], name='activity_task_completion_proof_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='activity_task_completion_pkey')
    )
    op.drop_table('activity_task_completions')
    # ### end Alembic commands ###
