"""add transaction, subsciption models

Revision ID: e8e0646f9e82
Revises: 62f46c3556a7
Create Date: 2024-06-09 13:13:21.074014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8e0646f9e82'
down_revision: Union[str, None] = '62f46c3556a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bracelet_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'OUTCOME', name='transactiontype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'DECLINED', name='transactionstatus'), server_default='PENDING', nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['telegram_id'], ['user.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bracelet_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('started_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('will_end_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['user.telegram_id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['bracelet_transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_payment')
    op.drop_table('user_payout')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_payout',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('reason', postgresql.ENUM('REFERRAL', 'ACTIVITY', 'OTHER', name='payoutreason'), autoincrement=False, nullable=False),
    sa.Column('amount_rub', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('paid_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['user.telegram_id'], name='user_payout_telegram_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_payout_pkey')
    )
    op.create_table('user_payment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('yookassa_payment_info', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment_reason', postgresql.ENUM('BRACELET', 'OTHER', name='paymentreason'), autoincrement=False, nullable=False),
    sa.Column('amount_rub', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('paid_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['user.telegram_id'], name='user_payment_telegram_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_payment_pkey')
    )
    op.drop_table('bracelet_subscription')
    op.drop_table('bracelet_transaction')
    # ### end Alembic commands ###
