"""proofs model update

Revision ID: fbfc9c42468f
Revises: c0a0526bb1a2
Create Date: 2024-06-09 22:30:18.984983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbfc9c42468f'
down_revision: Union[str, None] = 'c0a0526bb1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_completion_proof', sa.Column('photo_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('task_completion_proof', sa.Column('caption', sa.Text(), nullable=True))
    op.drop_column('task_completion_proof', 'media')
    op.drop_column('task_completion_proof', 'message_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_completion_proof', sa.Column('message_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('task_completion_proof', sa.Column('media', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('task_completion_proof', 'caption')
    op.drop_column('task_completion_proof', 'photo_ids')
    # ### end Alembic commands ###
